// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using HireAProfessional.Data.Common.Repositories;
using HireAProfessional.Data.Models;
using HireAProfessional.Data.Repositories;
using HireAProfessional.Services.Data;
using HireAProfessional.Web.ViewModels.Comments;
using HireAProfessionalML.Model;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RestSharp;

namespace HireAProfessionalML.ConsoleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var url = "http://localhost";

            var client = new RestClient(url);
            var request = new RestRequest(Method.GET);
            IRestResponse response = client.Execute(request);

            var comments = JsonConvert.DeserializeObject<ICollection<CommentViewModel>>(response.Content);
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                SentimentText = @"==RUDE== Dude, you are rude upload that carl picture back, or else.",
                LoggedIn = @"TRUE",
            };

            foreach (var comment in comments)
            {
                sampleData.SentimentText = comment.Content;
                var predictionResult = ConsumeModel.Predict(sampleData);

                Console.WriteLine("Using model to make single prediction -- Comparing actual Sentiment with predicted Sentiment from sample data...\n\n");
                Console.WriteLine($"SentimentText: {sampleData.SentimentText}");
                Console.WriteLine($"LoggedIn: {sampleData.LoggedIn}");
                Console.WriteLine($"\n\nPredicted Sentiment value {predictionResult.Prediction} \nPredicted Sentiment scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            }

            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        public static void Bot()
        {

        }
    }
}
